# Generated by Django 4.2.6 on 2023-11-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stud_id', models.AutoField(primary_key=True, serialize=False)),
                ('stud_name', models.CharField(max_length=100)),
                ('stud_email', models.CharField(max_length=100)),
                ('stud_contact', models.BigIntegerField()),
                ('stud_address', models.TextField()),
            ],
        ),
    ]
